/**
 *
 */
var Config = require('./config-base');
module.exports = new Config({
  local: {
    // semanticApiService: 'https://robot.rxhui.com/robot/semantic/semantic-api-service',
    semanticApiService:'http://semantic-api-service:31001',
    //marketPredictionService:'http://10.0.0.86:31001',
    marketPredictionService:'http://stock-newsanalysis-service:31001',
    metadataDimDwService:'http://metadata-dim-dw-service:31001',
    // semanticApiService:'http://staging.robot.jinhui001.com/robot/semantic/semantic-api-service',
    stockAnalysisService:'http://stock-analysis-service:31001',
    dwDbService:'http://dw-db-service:31001',
    // stockAnalysisService: 'http://staging.robot.jinhui001.com:8080/robot/semantic/stock-analysis-service',
    // reportCompositeService: 'http://report-composite-service:31001',
    // reportCompositeService: 'http://10.0.0.105:10030/reportUrl',
    //reportCompositeService: 'http://10.0.0.22:10035/reportUrl',
    reportCompositeService: 'http://module-template.rxhui.com/reportUrl',
    semanticDatacenterServic: 'http://semantic-datacenter-service:31001',
    semanticCompositeService: 'http://semantic-composite-service:31001',
    financeStatementeService:'http://finance-theme-service:31001',
    financeThemDwService:'http://finance-theme-dw-service:31001',
    // financeThemDwService:'https://robot.rxhui.com/robot/semanticfinance-theme-dw-service',
    robotApiUrl: 'http://dev.robot.jinhui001.com:8080/robot/semantic/semantic-api-service',
    logService: 'http://10.0.0.21:9097',
    aiApiService: 'http://ai-api-service:31001',
    // stockAnalysisService:'http://robot.rxhui.com/robot/semantic/stock-analysis-service',
    // stockAnalysisService:'http://robot.rxhui.com/robot/semantic/TechnichalAnalysis',
    quota: 'http://quota.zq88.cn',
    host: 'http://127.0.0.1:31001',
    resource: "http://127.0.0.1:31001",
    h5ApiUrl: 'http://c-project-dev.jinhui001.com',
    bigSearchUrl:'http://10.0.0.22:10031',
    logLevel: "info",
    autoReportIndustry:'http://report.rxhui.com'
  },
  dev: {
    stockAnalysisService: 'http://stock-analysis-service:31001',
    semanticApiService: 'http://semantic-api-service:31001',
    marketPredictionService:'http://stock-newsanalysis-service:31001',
    dwDbService:'http://dw-db-service:31001',
    metadataDimDwService:'http://metadata-dim-dw-service:31001',
    semanticDatacenterServic: 'http://semantic-datacenter-service:31001',
    semanticCompositeService: 'http://semantic-composite-service:31001',
    reportCompositeService: 'http://report-composite-service:31001',
    financeStatementeService:'http://finance-theme-service:31001',
    financeThemDwService:'http://finance-theme-dw-service:31001',
    robotApiUrl: 'http://dev.robot.jinhui001.com:8080/robot/semantic/semantic-api-service',
    logService: 'http://10.0.0.21:9097',
    aiApiService: 'http://ai-api-service:31001',
    quota: 'http://quota.zq88.cn',
    host: 'http://10.0.0.22:10029',
    resource: "http://10.0.0.22:10029",
    h5ApiUrl: 'http://c-project-dev.jinhui001.com',
    bigSearchUrl:'http://10.0.0.22:10031',
    logLevel: "info",
    autoReportIndustry:'http://report.rxhui.com'
  },
  staging: {
    stockAnalysisService: 'http://stock-analysis-service:31001',
    semanticApiService: 'http://semantic-api-service:31001',
    marketPredictionService:'http://stock-newsanalysis-service:31001',
    metadataDimDwService:'http://metadata-dim-dw-service:31001',
    dwDbService:'http://dw-db-service:31001',
    semanticDatacenterServic: 'http://semantic-datacenter-service:31001',
    reportCompositeService: 'http://report-composite-service:31001',
    semanticCompositeService: 'http://semantic-composite-service:31001',
    financeStatementeService:'http://finance-theme-service:31001',
    financeThemDwService:'http://finance-theme-dw-service:31001',
    robotApiUrl: 'http://staging.robot.jinhui001.com/robot/semantic/semantic-api-service',
    logService: 'http://10.0.0.21:9097',
    aiApiService: 'http://ai-api-service:31001',
    quota: 'http://quota.zq88.cn',
    host: 'http://template.jinhui001.com',
    resource: "http://template.jinhui001.com",
    h5ApiUrl: 'http://10.0.0.105:8086',
    bigSearchUrl:'http://10.0.0.105:10027',
    logLevel: "info",
    autoReportIndustry:'http://report.rxhui.com'
  },
  production: {
    stockAnalysisService: 'http://stock-analysis-service:31001',
    semanticApiService: 'http://semantic-api-service:31001',
    marketPredictionService:'http://stock-newsanalysis-service:31001',
    metadataDimDwService:'http://metadata-dim-dw-service:31001',
    dwDbService:'http://dw-db-service:31001',
    reportCompositeService: 'http://report-composite-service:31001',
    semanticDatacenterServic: 'http://semantic-datacenter-service:31001',
    semanticCompositeService: 'http://semantic-composite-service:31001',
    financeStatementeService:'http://finance-theme-service:31001',
    financeThemDwService:'http://finance-theme-dw-service:31001',
    robotApiUrl: 'https://robot.rxhui.com/robot/semantic/semantic-api-service',
    logService: 'http://node-log.rxhui.com',
    aiApiService: 'http://ai-api-service:31001',
    quota: 'http://quota.zq88.cn',
    host: 'https://template.rxhui.com',
    resource: "https://template.rxhui.com",
    h5ApiUrl: 'http://c-project.rxhui.com',
    bigSearchUrl:'http://big-data.rxhui.com',
    logLevel: "info",
    autoReportIndustry:'http://report.rxhui.com'
  },
  ali: {
    semanticApiService: 'http://semantic-api-service:31001',
    marketPredictionService:'http://stock-newsanalysis-service:31001',
    stockAnalysisService: 'http://stock-analysis-service:31001',
    metadataDimDwService:'http://metadata-dim-dw-service:31001',
    dwDbService:'http://dw-db-service:31001',
    semanticDatacenterServic: 'http://semantic-datacenter-service:31001',
    semanticCompositeService: 'http://semantic-composite-service:31001',
    financeStatementeService:'http://finance-theme-service:31001',
    financeThemDwService:'http://finance-theme-dw-service:31001',
    logService: 'http://node-log.rxhui.com',
    aiApiService: 'http://ai-api-service:31001',
    quota: 'http://quota.zq88.cn',
    host: 'https://robot-module.rxhui.com',
    resource: "https://robot-module.rxhui.com",
    h5ApiUrl: 'http://c-project.rxhui.com',
    bigSearchUrl:'http://big-data.rxhui.com',
    logLevel: "info",
    autoReportIndustry:'http://report.rxhui.com'
  },
  logDir: process.cwd() + '/../logs/',

});
