export const userInfo = {
	'department': '-',
	'email': '-',
	'menu_auth': [{
		'icon': '',
		'id': 440534,
		'isMenu': 1,
		'menus': [{
			'icon': 'pending',
			'id': 884784,
			'isMenu': 1,
			'menus': [],
			'name': '待处理项目',
			'pid': 440534,
			'remark': '待处理项目',
			'sortVal': 2,
			'url': '/sdl/dorado/pending'
		}, {
			'icon': 'project',
			'id': 440542,
			'isMenu': 1,
			'menus': [],
			'name': '我的项目',
			'pid': 440534,
			'remark': '我的项目-RD视图',
			'sortVal': 0,
			'url': '/sdl/dorado'
		}, {
			'icon': 'project',
			'id': 884968,
			'isMenu': 1,
			'menus': [],
			'name': '所有项目',
			'pid': 440534,
			'remark': '所有项目-SDL工程师视图',
			'sortVal': 1,
			'url': '/sdl/dorado'
		}, {
			'icon': 'approve',
			'id': 2307572,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 440576,
				'isMenu': 1,
				'menus': [],
				'name': 'Odin准入',
				'pid': 2307572,
				'remark': 'Odin准入',
				'sortVal': 0,
				'url': '/sdl/dorado/odin'
			}],
			'name': '审批中心',
			'pid': 440534,
			'remark': '审批中心',
			'sortVal': 3,
			'url': '/sdl/dorado/approve'
		}],
		'name': '安全评估',
		'pid': 0,
		'remark': '无实际接口菜单目录',
		'sortVal': 1,
		'url': '/sdl/dorado'
	}, {
		'icon': '',
		'id': 440540,
		'isMenu': 1,
		'menus': [{
			'icon': 'solution',
			'id': 440550,
			'isMenu': 1,
			'menus': [],
			'name': '安全方案',
			'pid': 440540,
			'remark': '无实际接口菜单目录',
			'sortVal': 2,
			'url': '/sdl/dolphin/solution'
		}, {
			'icon': 'vul',
			'id': 440548,
			'isMenu': 1,
			'menus': [],
			'name': '漏洞知识',
			'pid': 440540,
			'remark': '无实际接口菜单目录',
			'sortVal': 1,
			'url': '/sdl/dolphin/vulnerability'
		}, {
			'icon': 'test',
			'id': 440670,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2299491,
				'isMenu': 1,
				'menus': [],
				'name': '移动端规则库',
				'pid': 440670,
				'remark': '移动端规则库',
				'sortVal': 2,
				'url': '/sdl/dolphin/testBaseManagement/mobileRule'
			}, {
				'icon': '',
				'id': 2299490,
				'isMenu': 1,
				'menus': [],
				'name': '黑盒插件库',
				'pid': 440670,
				'remark': '黑盒插件库',
				'sortVal': 1,
				'url': '/sdl/dolphin/testBaseManagement/blackPlugin'
			}, {
				'icon': '',
				'id': 2299489,
				'isMenu': 1,
				'menus': [],
				'name': '白盒规则库',
				'pid': 440670,
				'remark': '白盒规则库',
				'sortVal': 0,
				'url': '/sdl/dolphin/testBaseManagement/whiteRule'
			}, {
				'icon': '',
				'id': 2300623,
				'isMenu': 1,
				'menus': [],
				'name': 'Cobra规则库',
				'pid': 440670,
				'remark': 'Cobra规则库',
				'sortVal': 3,
				'url': '/sdl/dolphin/testBaseManagement/cobraRule'
			}, {
				'icon': '',
				'id': 2300624,
				'isMenu': 1,
				'menus': [],
				'name': 'Fatbird规则库',
				'pid': 440670,
				'remark': 'Fatbird规则库',
				'sortVal': 4,
				'url': '/sdl/dolphin/testBaseManagement/fatbirdRule'
			}],
			'name': '测试库管理',
			'pid': 440540,
			'remark': '测试库管理',
			'sortVal': 5,
			'url': '/sdl/dolphin/testBaseManagement'
		}, {
			'icon': 'threat',
			'id': 440668,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2299670,
				'isMenu': 1,
				'menus': [],
				'name': '威胁列表',
				'pid': 440668,
				'remark': '威胁列表',
				'sortVal': 1,
				'url': '/sdl/dolphin/threatBaseManagement/threatList'
			}, {
				'icon': '',
				'id': 2299669,
				'isMenu': 1,
				'menus': [],
				'name': '攻击面',
				'pid': 440668,
				'remark': '攻击面',
				'sortVal': 0,
				'url': '/sdl/dolphin/threatBaseManagement/attackSurface'
			}],
			'name': '威胁库管理',
			'pid': 440540,
			'remark': '威胁库管理',
			'sortVal': 4,
			'url': '/sdl/dolphin/threatBaseManagement'
		}, {
			'icon': 'knowledge',
			'id': 440674,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2299671,
				'isMenu': 1,
				'menus': [],
				'name': '漏洞知识库',
				'pid': 440674,
				'remark': '漏洞知识库',
				'sortVal': 0,
				'url': '/sdl/dolphin/knowledgeBaseManagement/vulknowledge'
			}, {
				'icon': '',
				'id': 2299672,
				'isMenu': 1,
				'menus': [],
				'name': '安全方案库',
				'pid': 440674,
				'remark': '安全方案库',
				'sortVal': 1,
				'url': '/sdl/dolphin/knowledgeBaseManagement/slnknowledge'
			}],
			'name': '知识库管理',
			'pid': 440540,
			'remark': '知识库管理',
			'sortVal': 6,
			'url': '/sdl/dolphin/knowledgeBaseManagement'
		}, {
			'icon': 'mooc',
			'id': 2300442,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2347147,
				'isMenu': 1,
				'menus': [],
				'name': '我的课程',
				'pid': 2300442,
				'remark': '我的课程',
				'sortVal': 0,
				'url': '/sdl/dolphin/mooc/video/mycourse'
			}, {
				'icon': '',
				'id': 2347148,
				'isMenu': 1,
				'menus': [],
				'name': '所有课程',
				'pid': 2300442,
				'remark': '所有课程',
				'sortVal': 0,
				'url': '/sdl/dolphin/mooc/video/allcourse'
			}],
			'name': '视频课程',
			'pid': 440540,
			'remark': '视频课程',
			'sortVal': 3,
			'url': '/sdl/dolphin/mooc'
		}, {
			'icon': 'baseline',
			'id': 2299492,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2299723,
				'isMenu': 1,
				'menus': [],
				'name': '项目等级规则',
				'pid': 2299492,
				'remark': '项目等级规则',
				'sortVal': 3,
				'url': '/sdl/dolphin/baselineManagement/projectLevelRule'
			}, {
				'icon': '',
				'id': 2299722,
				'isMenu': 1,
				'menus': [],
				'name': '基线生成规则',
				'pid': 2299492,
				'remark': '基线生成规则',
				'sortVal': 2,
				'url': '/sdl/dolphin/baselineManagement/baselineRule'
			}, {
				'icon': '',
				'id': 2299721,
				'isMenu': 1,
				'menus': [],
				'name': '基线列表',
				'pid': 2299492,
				'remark': '基线列表',
				'sortVal': 1,
				'url': '/sdl/dolphin/baselineManagement/baseline'
			}],
			'name': '基线库管理',
			'pid': 440540,
			'remark': '基线库管理',
			'sortVal': 7,
			'url': '/sdl/dolphin/baselineManagement'
		}],
		'name': '知识培训',
		'pid': 0,
		'remark': '无接口菜单目录',
		'sortVal': 6,
		'url': '/sdl/dolphin'
	}, {
		'icon': '',
		'id': 440538,
		'isMenu': 1,
		'menus': [{
			'icon': 'group',
			'id': 2306342,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2306343,
				'isMenu': 1,
				'menus': [],
				'name': '团队项目',
				'pid': 2306342,
				'remark': '团队项目',
				'sortVal': 0,
				'url': '/sdl/octopus/group/project'
			}, {
				'icon': '',
				'id': 2306345,
				'isMenu': 1,
				'menus': [],
				'name': '漏洞列表',
				'pid': 2306342,
				'remark': '漏洞列表',
				'sortVal': 2,
				'url': '/sdl/octopus/group/vulnerability'
			}, {
				'icon': '',
				'id': 2306344,
				'isMenu': 1,
				'menus': [],
				'name': '扫描任务',
				'pid': 2306342,
				'remark': '扫描任务',
				'sortVal': 1,
				'url': '/sdl/octopus/group/task'
			}],
			'name': '团队扫描',
			'pid': 440538,
			'remark': '团队扫描',
			'sortVal': 1,
			'url': '/sdl/octopus/group'
		}, {
			'icon': 'mob-vul',
			'id': 2306341,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 440742,
				'isMenu': 1,
				'menus': [],
				'name': '我的任务',
				'pid': 2306341,
				'remark': '我的任务',
				'sortVal': 1,
				'url': '/sdl/octopus/task'
			}, {
				'icon': '',
				'id': 440744,
				'isMenu': 1,
				'menus': [],
				'name': '漏洞列表',
				'pid': 2306341,
				'remark': '漏洞列表',
				'sortVal': 2,
				'url': '/sdl/octopus/vulnerability'
			}, {
				'icon': '',
				'id': 896454,
				'isMenu': 1,
				'menus': [],
				'name': '用户授权',
				'pid': 2306341,
				'remark': '用户授权',
				'sortVal': 3,
				'url': '/sdl/octopus/user/auth'
			}, {
				'icon': '',
				'id': 896990,
				'isMenu': 1,
				'menus': [],
				'name': '用户面板',
				'pid': 2306341,
				'remark': '用户面板',
				'sortVal': 0,
				'url': '/sdl/octopus/statistic'
			}],
			'name': '个人扫描',
			'pid': 440538,
			'remark': '个人扫描',
			'sortVal': 0,
			'url': '/sdl/octopus/personal'
    }, {
			'icon': 'mob-vul',
			'id': 23063411,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 4407421,
				'isMenu': 1,
				'menus': [],
				'name': '扫描任务',
				'pid': 23063411,
				'remark': '扫描任务',
				'sortVal': 1,
				'url': '/sdl/octopus/initiative/task'
			}, {
				'icon': '',
				'id': 4407441,
				'isMenu': 1,
				'menus': [],
				'name': '漏洞列表',
				'pid': 23063411,
				'remark': '漏洞列表',
				'sortVal': 2,
				'url': '/sdl/octopus/initiative/list'
			}],
			'name': '主动扫描',
			'pid': 440538,
			'remark': '主动扫描',
			'sortVal': 2,
			'url': '/sdl/octopus/initiative/task'
		}],
		'name': '黑盒扫描',
		'pid': 0,
		'remark': '无接口菜单',
		'sortVal': 2,
		'url': '/sdl/octopus'
	}, {
		'icon': '',
		'id': 440536,
		'isMenu': 1,
		'menus': [{
			'icon': 'test',
			'id': 2304539,
			'isMenu': 1,
			'menus': [],
			'name': '检测规则管理',
			'pid': 440536,
			'remark': '检测规则管理',
			'sortVal': 3,
			'url': '/sdl/ratel/rule'
		}, {
			'icon': 'fp',
			'id': 2304538,
			'isMenu': 1,
			'menus': [],
			'name': '误报规则管理',
			'pid': 440536,
			'remark': '误报规则管理',
			'sortVal': 2,
			'url': '/sdl/ratel/falsePositive'
		}, {
			'icon': 'apk',
			'id': 2304537,
			'isMenu': 1,
			'menus': [],
			'name': '自助检测',
			'pid': 440536,
			'remark': '自助检测',
			'sortVal': 0,
			'url': '/sdl/ratel/selfService'
		}, {
			'icon': 'app',
			'id': 2304536,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2304543,
				'isMenu': 1,
				'menus': [],
				'name': '漏洞列表',
				'pid': 2304536,
				'remark': '漏洞列表',
				'sortVal': 2,
				'url': '/sdl/ratel/release/vulnerability'
			}, {
				'icon': '',
				'id': 2304542,
				'isMenu': 1,
				'menus': [],
				'name': '检测任务',
				'pid': 2304536,
				'remark': '检测任务',
				'sortVal': 1,
				'url': '/sdl/ratel/release/task'
			}, {
				'icon': '',
				'id': 2304541,
				'isMenu': 1,
				'menus': [],
				'name': '我的项目',
				'pid': 2304536,
				'remark': '我的项目',
				'sortVal': 0,
				'url': '/sdl/ratel/release/project'
			}],
			'name': '发版检测',
			'pid': 440536,
			'remark': '发版检测',
			'sortVal': 1,
			'url': '/sdl/ratel/release'
		}, {
			'icon': 'sdk',
			'id': 2304540,
			'isMenu': 1,
			'menus': [{
				'icon': '',
				'id': 2304545,
				'isMenu': 1,
				'menus': [],
				'name': '应用权限管理',
				'pid': 2304540,
				'remark': '应用权限管理',
				'sortVal': 1,
				'url': '/sdl/ratel/asset/permission'
			}, {
				'icon': '',
				'id': 2304544,
				'isMenu': 1,
				'menus': [],
				'name': 'SDK管理',
				'pid': 2304540,
				'remark': 'SDK管理',
				'sortVal': 0,
				'url': '/sdl/ratel/asset/sdk'
			}],
			'name': '资产管理',
			'pid': 440536,
			'remark': '资产管理',
			'sortVal': 4,
			'url': '/sdl/ratel/asset'
		}],
		'name': 'APP检测',
		'pid': 0,
		'remark': '无实际接口菜单目录',
		'sortVal': 5,
		'url': '/sdl/ratel'
	}, {
		'icon': '',
		'id': 440546,
		'isMenu': 1,
		'menus': [{
			'icon': 'mob-task',
			'id': 897160,
			'isMenu': 1,
			'menus': [],
			'name': '检测任务',
			'pid': 440546,
			'remark': '检测任务',
			'sortVal': 1,
			'url': '/sdl/otter/task'
		}, {
			'icon': 'mob-vul',
			'id': 897162,
			'isMenu': 1,
			'menus': [],
			'name': '漏洞列表',
			'pid': 440546,
			'remark': '漏洞列表',
			'sortVal': 2,
			'url': '/sdl/otter/vul'
		}, {
			'icon': 'otter-proj',
			'id': 897158,
			'isMenu': 1,
			'menus': [],
			'name': '我的项目',
			'pid': 440546,
			'remark': '我的项目',
			'sortVal': 0,
			'url': '/sdl/otter/project'
		}, {
			'icon': 'otter-proj',
			'id': 897,
			'isMenu': 1,
			'menus': [],
			'name': '自助扫描',
			'pid': 440546,
			'remark': '自助扫描',
			'sortVal': 7,
			'url': '/sdl/otter/selfScan'
		}, {
			'icon': 'statistic',
			'id': 899262,
			'isMenu': 1,
			'menus': [],
			'name': 'Kibana数据统计',
			'pid': 440546,
			'remark': 'Kibana数据统计',
			'sortVal': 5,
			'url': '/sdl/otter/statistic'
		}, {
			'icon': 'test',
			'id': 897710,
			'isMenu': 1,
			'menus': [],
			'name': '检测规则管理',
			'pid': 440546,
			'remark': '检测规则管理',
			'sortVal': 4,
			'url': '/sdl/otter/rule'
		}, {
			'icon': 'fp',
			'id': 897702,
			'isMenu': 1,
			'menus': [],
			'name': '误报规则管理',
			'pid': 440546,
			'remark': '误报规则管理',
			'sortVal': 3,
			'url': '/sdl/otter/falsePositive'
		}],
		'name': '白盒检测',
		'pid': 0,
		'remark': '无实际接口',
		'sortVal': 3,
		'url': '/sdl/otter'
	}, {
		'icon': '',
		'id': 2313412,
		'isMenu': 1,
		'menus': [{
			'icon': '',
			'id': 2313413,
			'isMenu': 1,
			'menus': [],
			'name': '代码扫描',
			'pid': 2313412,
			'remark': '代码扫描',
			'sortVal': 0,
			'url': '/sdl/devsecops/code/scan'
		}],
		'name': 'DevSecOps',
		'pid': 0,
		'remark': '无接口菜单目录',
		'sortVal': 4,
		'url': '/sdl/devsecops'
	}, {
		'icon': '',
		'id': 1014284,
		'isMenu': 1,
		'menus': [{
			'icon': 'intra',
			'id': 2308843,
			'isMenu': 1,
			'menus': [{
				'icon': 'user',
				'id': 2313406,
				'isMenu': 1,
				'menus': [],
				'name': '月报',
				'pid': 2308843,
				'remark': '月报',
				'sortVal': 0,
				'url': '/sdl/ocean/intra/report'
			}, {
				'icon': '',
				'id': 2347330,
				'isMenu': 1,
				'menus': [],
				'name': '视频指标',
				'pid': 2308843,
				'remark': '视频指标',
				'sortVal': 3,
				'url': '/sdl/ocean/intra/video'
			}, {
				'icon': '',
				'id': 2312858,
				'isMenu': 1,
				'menus': [],
				'name': '白盒指标',
				'pid': 2308843,
				'remark': '白盒指标',
				'sortVal': 1,
				'url': '/sdl/ocean/intra/fatbird'
			}, {
				'icon': '',
				'id': 2308844,
				'isMenu': 1,
				'menus': [],
				'name': '基线指标',
				'pid': 2308843,
				'remark': '基线指标',
				'sortVal': 0,
				'url': '/sdl/ocean/intra/baseline'
			}],
			'name': '内部指标',
			'pid': 1014284,
			'remark': '内部指标',
			'sortVal': 2,
			'url': '/sdl/ocean/intra'
		}, {
			'icon': 'dept',
			'id': 2304744,
			'isMenu': 1,
			'menus': [],
			'name': '部门看板',
			'pid': 1014284,
			'remark': '部门看板',
			'sortVal': 1,
			'url': '/sdl/ocean/department'
		}, {
			'icon': 'global',
			'id': 2300626,
			'isMenu': 1,
			'menus': [],
			'name': '全局指标',
			'pid': 1014284,
			'remark': '全局指标',
			'sortVal': 0,
			'url': '/sdl/ocean/global'
		}],
		'name': '指标监控',
		'pid': 0,
		'remark': '指标监控',
		'sortVal': 8,
		'url': '/sdl/ocean'
	}, {
		'icon': '',
		'id': 1014283,
		'isMenu': 1,
		'menus': [{
			'icon': 'domain',
			'id': 2347172,
			'isMenu': 1,
			'menus': [],
			'name': '办公网域名',
			'pid': 1014283,
			'remark': '办公网域名',
			'sortVal': 3,
			'url': '/sdl/cachalot/it'
		}, {
			'icon': 'cachalot-git',
			'id': 2350540,
			'isMenu': 1,
			'menus': [],
			'name': 'Git',
			'pid': 1014283,
			'remark': 'Git',
			'sortVal': 4,
			'url': '/sdl/cachalot/git'
		}, {
			'icon': 'mob-vul',
			'id': 1014285,
			'isMenu': 1,
			'menus': [],
			'name': '安全漏洞',
			'pid': 1014283,
			'remark': '安全漏洞',
			'sortVal': 0,
			'url': '/sdl/cachalot/vulnerability'
		}, {
			'icon': 'domain',
			'id': 2304530,
			'isMenu': 1,
			'menus': [],
			'name': '公网域名',
			'pid': 1014283,
			'remark': '公网域名',
			'sortVal': 2,
			'url': '/sdl/cachalot/domain'
		}, {
			'icon': 'online-vul',
			'id': 2313945,
			'isMenu': 1,
			'menus': [],
			'name': 'R2分析',
			'pid': 1014283,
			'remark': 'R2分析',
			'sortVal': 1,
			'url': '/sdl/cachalot/onlineVul'
		}, {
			'icon': 'oct-blood',
			'id': 2299674,
			'isMenu': 1,
			'menus': [],
			'name': '黑盒数据源',
			'pid': 1014283,
			'remark': '黑盒数据源',
			'sortVal': 5,
			'url': '/sdl/cachalot/octopusAsset'
		}],
		'name': '资产库',
		'pid': 0,
		'remark': '资产库',
		'sortVal': 7,
		'url': '/sdl/cachalot'
	}, {
		'icon': '',
		'id': 1014385,
		'isMenu': 1,
		'menus': [{
			'icon': 'user',
			'id': 2347113,
			'isMenu': 1,
			'menus': [],
			'name': '视频后台管理',
			'pid': 1014385,
			'remark': '视频后台管理',
			'sortVal': 0,
			'url': '/sdl/admin/video'
		}, {
			'icon': 'user',
			'id': 1014391,
			'isMenu': 1,
			'menus': [],
			'name': '安全BP管理',
			'pid': 1014385,
			'remark': '安全BP管理',
			'sortVal': 0,
			'url': '/sdl/admin/securityBp'
		}, {
			'icon': 'user',
			'id': 2312992,
			'isMenu': 1,
			'menus': [{
				'icon': 'user',
				'id': 2312999,
				'isMenu': 1,
				'menus': [],
				'name': '安全BP分配规则',
				'pid': 2312992,
				'remark': '安全BP分配规则',
				'sortVal': 0,
				'url': '/sdl/admin/intra/baseline'
			}],
			'name': '基线后台管理',
			'pid': 1014385,
			'remark': '基线后台管理',
			'sortVal': 0,
			'url': '/sdl/admin/intra'
		}],
		'name': '后台管理',
		'pid': 0,
		'remark': '后台管理',
		'sortVal': 9,
		'url': '/sdl/admin'
	}],
	'roles': ['sdl_engineer', 'rd_engineer'],
	'username': 'test',
	'username_zh': '测试账户'
}
