export const getVulList = '/cachalot/vul/list'
export const updateVul = '/cachalot/vul/update'
export const deleteVul = '/cachalot/vul/delete'
export const domainList = '/cachalot/domain/list'
export const updateDomain = '/cachalot/domain/update'

export const getOnlineVulList = '/cachalot/vul/onlineVul/list'
export const getOneOnlineVul = '/cachalot/vul/onlineVul/getOne'
export const getPositionOnlineVul = '/cachalot/vul/onlineVul/position'
export const updateOnlineVul = '/cachalot/vul/onlineVul/update'

export const dimqueryDomain = '/cachalot/domain/dimquery'
export const modifyDomain = '/cachalot/domain/modify'
export const modifyItDomain = '/cachalot/it/modify'
export const getItDomain = '/cachalot/it/list'
export const updateItDomain = '/cachalot/it/update'
export const getGitDomain = '/cachalot/git/list'
export const getGitSdkInfo = '/cachalot/git/sdkInfo'
export const getGitSensitive = '/cachalot/git/sensitive'
