export const getTaskList = '/octopus/task/list'

export const createTask = '/octopus/task/create'
export const deleteTask = '/octopus/task/delete'
export const updateTask = '/octopus/task/update'
export const pluginsTaskList = '/octopus/task/plugins'
export const periodTaskTime = '/octopus/task/period'
export const execTask = '/octopus/task/exec'
export const statusTask = '/octopus/task/status'

export const startTask = '/octopus/task/start'
export const stopTask = '/octopus/task/stop'
export const retestTask = '/octopus/task/retest'

export const taskReport = '/octopus/task/report'

export const getTaskVulList = '/octopus/vulnerability/list'
export const taskVulMisinformation = '/octopus/task/vulnerability/misinformation'

export const getVulList = '/octopus/vulnerability/list'
export const deleteVul = '/octopus/vulnerability/delete'
export const vulMisinformation = '/octopus/vulnerability/misinformation'
export const preSearch = '/octopus/vulnerability/preSearch'
export const check = '/octopus/vulnerability/check'
export const repair = '/octopus/vulnerability/repair'
export const push = '/octopus/vulnerability/push'

export const userAuthList = '/octopus/user/auth/list'
export const userAuthcreate = '/octopus/user/auth/create'
export const userAuthUpdate = '/octopus/user/auth/update'
export const userAuthDelete = '/octopus/user/auth/delete'
export const userAuthTemplete = '/octopus/user/auth/templete'
export const getUserAuth = '/octopus/user/auth/getone'
export const signAgreementUserAuth = '/octopus/user/auth/signAgreement'

export const authInfoStatistic = '/octopus/statistic/authInfo'
export const taskCountStatistic = '/octopus/statistic/taskCount'
export const vulCountStatistic = '/octopus/statistic/vulCount'
export const targetCountStatistic = '/octopus/statistic/targetCount'
export const getGroupProjectList = '/octopus/group/project/list'
export const createGroupProject = '/octopus/group/project/create'
export const updateGroupProject = '/octopus/group/project/update'
export const getfollowerGroupProject = '/octopus/group/project/getfollower'
export const addfollowerGroupProject = '/octopus/group/project/addfollower'
export const getDetailGroupProjectByID = '/octopus/group/project/detail'
export const getTemplateByProjectId = '/octopus/group/template/getByProjectId'
export const newSession = '/octopus/group/template/new_session'
export const updateGroupFilter = '/octopus/group/template/update_filter'
export const getStatusGroupFilter = '/octopus/group/template/get_status_filter'
export const getResultGroupFilter = '/octopus/group/template/get_result_filter'
export const updateTemplateLocator = '/octopus/group/template/update_locator'
export const saveTemplateGroup = '/octopus/group/template/save'
export const reloadTemplateGroup = '/octopus/group/template/reload'
export const getGroupTask = '/octopus/group/task/list'
export const updateGroupTask = '/octopus/group/task/update'
export const getAllProjectGroup = '/octopus/group/project/getAll'
export const createDefaultProject = '/octopus/group/project/createDefault'
export const updateDefaultProject = '/octopus/group/project/updateDefault'
export const listVulnerability = '/octopus/group/vulnerability/list'
export const processVul = '/octopus/group/vulnerability/process'

// 主动扫描
export const createScanTask = '/octopus/self/scan/task/create'
export const getScanVulList = '/octopus/self/task/result/list'
export const getWebPluginScan = '/octopus/self/scan/web'
export const getHostPluginScan = '/octopus/self/scan/host'
