FROM registry.xiaojukeji.com/didionline/sec-sso-nginx:stable

COPY ./home-xiaoju-upm2-static /home/xiaoju/upm2-static
COPY ./home-xiaoju-upm2-static /home/xiaoju/aegis-static/src/project/auth/dist
COPY ./aegis-static-upm2.conf /home/xiaoju/nginx/conf/server_conf/

