export const VARIABLETABS = [
  {name: '基础变量', key: 0},
  {name: '输出变量', key: 1},
  {name: '匹配字典', key: 2},
  {name: '衍生变量', key: 3},
]

export const FLOWCONFIG = [
  {
    referenceType: 0,
    ptype: 'out',
    type: 'EXEC',
    name: '开始',
    nodeName: '开始',
    color: '#3d89f7',
    bgColor: '#ecf4fc',
    idCard: '0',
  },
  {
    referenceType: 99,
    ptype: 'out',
    type: 'EXEC',
    name: '结束',
    nodeName: '结束',
    color: '#006877',
    bgColor: '#CEF5E8',
    idCard: '1',
  },
  {
    referenceType: 2,
    ptype: 'out',
    type: 'EXEC',
    name: '规则集',
    nodeName: '请选择规则集',
    color: '#3d89f7',
    bgColor: '#ecf4fc',
    idCard: '2',
  },
  {
    referenceType: 3,
    ptype: 'out',
    type: 'EXEC',
    name: '评分卡',
    nodeName: '请选择评分卡',
    color: '#3d89f7',
    bgColor: '#ecf4fc',
    idCard: '3',
  },
  {
    referenceType: 4,
    ptype: 'out',
    type: 'EXEC',
    name: '矩阵',
    nodeName: '请选择矩阵',
    color: '#3d89f7',
    bgColor: '#ecf4fc',
    idCard: '4',
  },
  {
    referenceType: 1,
    ptype: 'out',
    type: 'EXEC',
    name: '衍生规则',
    nodeName: '请选择衍生规则',
    color: '#3d89f7',
    bgColor: '#ecf4fc',
    idCard: '5',
  },
  {
    ptype: 'in',
    type: 'REF',
    name: '条件',
    color: '#855000',
    bgColor: '#FFECB9',
    idCard: '6',
  },
]
