import Head from 'next/head'
import styles from '../../index.less'
import {useRouter} from 'next/router'
function body() {
  const router = useRouter()
  const queryParams = router.query
  return (
    <div>
      <Head>
        <title>借款协议</title>
      </Head>
      <div className={styles.content}>
        <p className={styles.tc}>
          <strong>
            <strong>(</strong>
          </strong>
          <strong>
            <strong>****银行股份有限公司)</strong>
          </strong>
        </p>
        <p className={styles.tc}>
          <strong>
            <strong>借款协议</strong>
          </strong>
        </p>

        <p>
          <strong>
            <strong>特别提醒：</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              请借款人在使用本协议项下的贷款服务前仔细阅读《借款协议》（以下简称
            </strong>
          </strong>
          <strong>
            <strong>&ldquo;</strong>
          </strong>
          <strong>
            <strong>本协议</strong>
          </strong>
          <strong>
            <strong>&rdquo;</strong>
          </strong>
          <strong>
            <strong>
              ，请特别注意协议中以粗体标注的内容部分）。一旦借款人签署本协议或使用贷款服务，即视为借款人已充分阅读并理解本协议所有条款的含义及相应法律后果，并同意受本协议约束。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第一条借款基本信息</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>贷款人名称：</strong>
          </strong>
          {queryParams.lender || 'lender'}
        </p>
        <p>
          <strong>
            <strong>借款人的姓名：</strong>
          </strong>
          {queryParams.name || 'name'}
        </p>
        <p>
          <strong>
            <strong>证件类型：</strong>
          </strong>
          {queryParams.certType || 'certType'}
        </p>
        <p>
          <strong>
            <strong>证件号码：</strong>
          </strong>
          {queryParams.certCode || 'certCode'}
        </p>
        <p>
          <strong>
            <strong>借</strong>
          </strong>
          <strong>
            <strong>款金额：</strong>
          </strong>
          {queryParams.amount || 'amount'}元
        </p>
        <p>
          <strong>
            <strong>借</strong>
          </strong>
          <strong>
            <strong>款期限：</strong>
          </strong>
          {queryParams.periods || 'periods'}期
        </p>
        <p>
          <strong>
            <strong>借款年利率：</strong>
          </strong>
          {queryParams.Rate || 'Rate'}/天
        </p>
        <p>
          <strong>
            <strong>代收担保费率</strong>
          </strong>
          (如有)
          <strong>
            <strong>：</strong>
          </strong>
          &nbsp;{queryParams.garantee || 'garantee'}
        </p>
        <p>
          <strong>
            <strong>贷款市场报价利率&nbsp;：</strong>
          </strong>
          <strong>
            <strong>{queryParams.lpr || 'lpr'}</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>综合年化利率：</strong>
          </strong>
          <strong>
            <strong>{queryParams.apr || 'apr'} </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>利率加减点：</strong>
          </strong>
          <strong>
            <strong>{queryParams.floatPoint || 'floatPoint'}</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>LPR</strong>
          </strong>
          <strong>
            <strong>更新时间：</strong>
          </strong>
          <strong>
            <strong>{queryParams.lprUpdateTime || 'lprUpdateTime'}</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>收款账户：</strong>
          </strong>
          {queryParams.bankCard || 'bankCard'}
        </p>
        <p>
          <strong>
            <strong>还款方式：</strong>
          </strong>
          {queryParams.repayType || 'repayType'}
        </p>
        <p>
          <strong>
            <strong>还款日：</strong>
          </strong>
          每月{queryParams.repayDay || 'repayDay'}日
        </p>
        <p>
          <strong>
            <strong>协议</strong>
          </strong>
          <strong>
            <strong>签署日期：</strong>
          </strong>
          {queryParams.signTime || 'signTime'}
        </p>
        <p>
          <strong>
            <strong>协议</strong>
          </strong>
          <strong>
            <strong>签订地</strong>
          </strong>
          <strong>
            <strong>点</strong>
          </strong>
          <strong>
            <strong>：</strong>
          </strong>
          {queryParams.signAddress || 'signAddress'}
        </p>
        <p>
          为了保护借款人的个人信息安全，本协议在展示时部分隐藏了借款人的身份信息，
          <strong>
            <strong>
              借款人知晓并同意本协议项下借款人的身份信息以借款人在
            </strong>
          </strong>
          <strong>
            <strong>贷款人处</strong>
          </strong>
          <strong>
            <strong>所留存的信息为准</strong>
          </strong>
          <strong>
            <strong>，</strong>
          </strong>
          <strong>
            <strong>借款人不得以此为由否认本协议的效力。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第二条本协议的签署方</strong>
          </strong>
        </p>
        <p>
          1、本协议的签署方为借款人及贷款人，双方同意将以数据电文的形式签署本协议并认可本协议的法律效力。
        </p>
        <p>
          2、借款人：&ldquo;借款人的姓名&rdquo;在本协议第一条中列明，借款人须为中国大陆地区居民，且具有完全民事权利能力和民事行为能力，并独立行使和承担本协议项下权利义务。
        </p>
        <p>
          3、贷款人：&ldquo;贷款人名称&rdquo;在本协议第一条中列明，贷款人是指拥有合法发放贷款资质的中国大陆地区的机构。
        </p>
        <p>
          4、本协议项下，可能由一个或多个具有放贷资质的金融机构单独或共同为借款人提供贷款服务。当多个具有放贷资质的金融机构共同作为贷款人向借款人提供贷款服务时，借款人不得因未与部分金融机构直接沟通或未直接与该部分金融机构签署本协议等为由拒绝偿还贷款；贷款人之间按照贷款资金出资比例共享对借款人的债权，任何一方均有权向借款人要求归还本协议项下全部贷款本息，借款人不得以此为由拒绝偿还贷款。
        </p>
        <p>
          <strong>
            <strong>第三条贷款额度</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>借款人申请</strong>
          </strong>
          <strong>
            <strong>借款</strong>
          </strong>
          <strong>
            <strong>
              ，贷款人根据借款人的信用状况、还款能力及对各要素的综合评估给予初始额度，该初始额度并不代表借款人可以从贷款人处实际取得的资金金额。
            </strong>
          </strong>
          <strong>
            <strong>借款人知悉并同意，</strong>
          </strong>
          <strong>
            <strong>借款人的</strong>
          </strong>
          <strong>
            <strong>贷款</strong>
          </strong>
          <strong>
            <strong>额度会因为</strong>
          </strong>
          <strong>
            <strong>贷款</strong>
          </strong>
          <strong>
            <strong>人</strong>
          </strong>
          <strong>
            <strong>对额度进行的相关操作</strong>
          </strong>
          <strong>
            <strong>或其他因素</strong>
          </strong>
          <strong>
            <strong>而</strong>
          </strong>
          <strong>
            <strong>变化</strong>
          </strong>
          <strong>
            <strong>，</strong>
          </strong>
          <strong>
            <strong>实际</strong>
          </strong>
          <strong>
            <strong>
              有效贷款额度以平台展示为准，贷款人可通过本协议约定的方式在额度调整之后通知借款人，但此项不构成贷款人义务。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>借款人在贷款人批准的</strong>
          </strong>
          <strong>
            <strong>有效贷款</strong>
          </strong>
          <strong>
            <strong>额度范围内，可随时</strong>
          </strong>
          <strong>
            <strong>申请提款</strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>四</strong>
          </strong>
          <strong>
            <strong>条放款先决条件</strong>
          </strong>
        </p>
        <p>
          1、本协议项下贷款（含分笔发放时的每笔贷款，如有）的发放均以借款人满足下列条件为前提。借款人未满足下列任一条件，贷款人有权拒绝向借款人发放相应贷款，但贷款人可以同意放弃部分条件或同意延期满足某一项或某几项条件：
        </p>
        <p>
          （1）贷款人批准的贷款额度在有效期内且本协议项下贷款人向借款人发放的贷款本金不超过贷款人批准的贷款额度；
        </p>
        <p>
          （2）本协议已经双方签署，且借款人根据贷款人要求签署所有必要文书，提供必要证明、单据等文件、资料，并完成相关手续，且前述文件、资料及相关手续持续合法有效；
        </p>
        <p>（3）借款人的资质、信用状况通过贷款人的审核；</p>
        <p>（4）借款人未出现任何影响或可能影响借款人偿付能力的重大不利情形；</p>
        <p>（5）借款人未出现任何违反本合同约定的情形；</p>
        <p>（6）贷款人要求的其他先决条件。</p>
        <p>
          2、贷款发放前，如因国家有关部门颁布的法律、法规、规章、规定、指引、通知（包括口头通知）、政策及其他规范性文件导致贷款人不能发放本协议项下贷款的，或者贷款人发现借款人提供虚假信息或资料、签章不真实，或者有其他足以危及贷款安全的重大情形的，贷款人有权停止发放贷款或解除本协议，该等情况不视为贷款人违约。
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>五</strong>
          </strong>
          <strong>
            <strong>条</strong>
          </strong>
          <strong>
            <strong>贷款发放</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1</strong>
          </strong>
          <strong>
            <strong>、贷款人批准借款人的贷款申请后</strong>
          </strong>
          <strong>
            <strong>
              ，将在合理时间内尽快将贷款资金发放至借款人所指定的收款账户
            </strong>
          </strong>
          <strong>
            <strong>(</strong>
          </strong>
          <strong>
            <strong>银行账户或支付机构支付账户</strong>
          </strong>
          <strong>
            <strong>)</strong>
          </strong>
          <strong>
            <strong>
              ，借款人应保证借款人指定的收款账户的安全性、真实性及有效性，贷款人
            </strong>
          </strong>
          <strong>
            <strong>发放贷款后</strong>
          </strong>
          <strong>
            <strong>，如因借款人</strong>
          </strong>
          <strong>
            <strong>所指定的收款</strong>
          </strong>
          <strong>
            <strong>
              账户原因导致银行退单、款项回退等情形的，已经产生的利息、手续费等费用由借款人自行承担。
            </strong>
          </strong>
        </p>
        <p>
          2、贷款人收到借款人指定的收款账户所属的银行机构或支付机构返回的成功回执之日为贷款发放日，视为借款人本人已经收到贷款资金，借款人应按照本协议的约定履行还款义务。
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>六</strong>
          </strong>
          <strong>
            <strong>条对账方式</strong>
          </strong>
        </p>
        <p>
          1、贷款人将向借款人发送或委托平台展示借据明细、还款计划、交易明细等交易文件，载明贷款金额、放款日期、还款期数、还款日期等交易信息。
          <strong>
            <strong>具体送达</strong>
          </strong>
          <strong>
            <strong>方式包括但不限于平台站内信、消息中心</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>微信</strong>
          </strong>
          <strong>
            <strong>公众号</strong>
          </strong>
          <strong>
            <strong>，或向借款人提供的手机号码</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>微</strong>
          </strong>
          <strong>
            <strong>信发送</strong>
          </strong>
          <strong>
            <strong>消息</strong>
          </strong>
          <strong>
            <strong>，但此项不构成贷款人的义务。</strong>
          </strong>
        </p>
        <p>
          2、
          <strong>
            <strong>
              借款人应及时查阅并主动核对借据明细、还款计划、交易明细。
            </strong>
          </strong>
          借款人不得以未查阅或未收到借据明细、还款计划、交易明细或该等文件中的任一项为由拒绝向贷款人偿还贷款。
        </p>
        <p>
          3、若借款人对交易文件内容有异义，应在收到上述信息10日内向贷款人或平台提出查询申请，同时应说明理由并提供证明文件。超过上述时限未提出异议的，视为对所有交易信息的确认。
        </p>
        <p>
          <strong>
            <strong>第七条</strong>
          </strong>
          <strong>
            <strong>借款期限</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              借款期限自贷款发放日起开始计算，至贷款人提供的交易文件中载明的最后一期还款日止。
            </strong>
          </strong>
          <strong>
            <strong>除</strong>
          </strong>
          <strong>
            <strong>贷款人事先同意之外，借款期限不可展期。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>八</strong>
          </strong>
          <strong>
            <strong>条还款</strong>
          </strong>
        </p>
        <p>1、还款方式</p>
        <p>
          除另有约定外，本协议项下贷款的还款方式为下述方式中的一种，具体以本协议第一条约定的还款方式为准。
        </p>
        <p>
          （1）等额本息：除最后一期外，每期以固定金额偿还贷款本息，贷款到期日归还剩余本金和利息；
        </p>
        <p>
          （2）等额本金：每期以固定金额偿还贷款本金，每期贷款利息按期初剩余贷款本金计算并逐期结清，两者合计即为每期的还款额，贷款到期日归还剩余本金和利息；
        </p>
        <p>
          （3）先息后本：每期偿付当期实际产生的利息，贷款到期日归还全部贷款本金和最后一期利息；
        </p>
        <p>2、还款日</p>
        <p>
          <strong>
            <strong>借款人需密切关注还款计划中确定的还款日期</strong>
          </strong>
          <strong>
            <strong>。请注意</strong>
          </strong>
          <strong>
            <strong>，</strong>
          </strong>
          <strong>
            <strong>借款人的</strong>
          </strong>
          <strong>
            <strong>首笔</strong>
          </strong>
          <strong>
            <strong>借款距首个还款日的时间可能不足一个月。</strong>
          </strong>
        </p>
        <p>3、到期还款</p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>1</strong>
          </strong>
          <strong>
            <strong>）</strong>
          </strong>
          <strong>
            <strong>手动还款</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>如借款人选择手动还款，</strong>
          </strong>
          <strong>
            <strong>应</strong>
          </strong>
          <strong>
            <strong>不晚于</strong>
          </strong>
          <strong>
            <strong>每月还款日当天</strong>
          </strong>
          <strong>
            <strong>将</strong>
          </strong>
          <strong>
            <strong>当期应</strong>
          </strong>
          <strong>
            <strong>还</strong>
          </strong>
          <strong>
            <strong>款</strong>
          </strong>
          <strong>
            <strong>项</strong>
          </strong>
          <strong>
            <strong>汇划至贷款人指定的还款账户。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>2</strong>
          </strong>
          <strong>
            <strong>）</strong>
          </strong>
          <strong>
            <strong>自动扣款</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>借款人授权贷款人通过</strong>
          </strong>
          <strong>
            <strong>指定的</strong>
          </strong>
          <strong>
            <strong>第三方支付公司或银行</strong>
          </strong>
          <strong>
            <strong>，</strong>
          </strong>
          <strong>
            <strong>从借款人的指定账户中</strong>
          </strong>
          <strong>
            <strong>自</strong>
          </strong>
          <strong>
            <strong>
              动扣划每期还款资金。如无特别约定，借款人同意选择自动扣款作为本合同项下贷款本息的默认偿还方式。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>借款人应与</strong>
          </strong>
          <strong>
            <strong>第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>另行签署相关支付服务协议，并在借款人</strong>
          </strong>
          <strong>
            <strong>所指定的还款账户（即借款人的</strong>
          </strong>
          <strong>
            <strong>第三方支付</strong>
          </strong>
          <strong>
            <strong>账户或借款人</strong>
          </strong>
          <strong>
            <strong>第三方支付账户</strong>
          </strong>
          <strong>
            <strong>所</strong>
          </strong>
          <strong>
            <strong>绑定的</strong>
          </strong>
          <strong>
            <strong>银行</strong>
          </strong>
          <strong>
            <strong>账户</strong>
          </strong>
          <strong>
            <strong>或借款人与贷款人约定的其他银行账户）</strong>
          </strong>
          <strong>
            <strong>中开通</strong>
          </strong>
          <strong>
            <strong>&ldquo;</strong>
          </strong>
          <strong>
            <strong>快捷支付</strong>
          </strong>
          <strong>
            <strong>&rdquo;</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>&ldquo;</strong>
          </strong>
          <strong>
            <strong>免密支付</strong>
          </strong>
          <strong>
            <strong>&rdquo;</strong>
          </strong>
          <strong>
            <strong>等功能以自动还款。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              借款人授权贷款人作为免密支付商户，按照本合同及上述支付服务协议的约定，于还款日起（含当日）向
            </strong>
          </strong>
          <strong>
            <strong>第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>发送扣款指令，从借款人</strong>
          </strong>
          <strong>
            <strong>所指定的还款账户</strong>
          </strong>
          <strong>
            <strong>中扣划当期应还款项（包括但不限于本金、利息、</strong>
          </strong>
          <strong>
            <strong>担保</strong>
          </strong>
          <strong>
            <strong>
              费、罚息、违约金等）至贷款人指定账户。在自动还款项下，借款人认可
            </strong>
          </strong>
          <strong>
            <strong>第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>无需执行借款人与</strong>
          </strong>
          <strong>
            <strong>第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>约定的支付密码、手机验证码等验证措施。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（3）</strong>
          </strong>
          <strong>
            <strong>
              借款人应充分考虑还款资金在不同银行、支付机构之间划转的在途时间，确保在本合同约定的还款日前至少1个工作日将用于支付利息、费用以及归还本金的资金足额存入
            </strong>
          </strong>
          <strong>
            <strong>借款人所指定的还款账户</strong>
          </strong>
          <strong>
            <strong>
              。贷款人扣划成功之日为借款人支付或偿还相应费用和贷款本金之日，扣划成功的金额为借款人支付和偿还的金额。
            </strong>
          </strong>
        </p>
        <p>
          （4）借款人使用自动扣款方式进行还款时，借款人所指定的还款账户必须有足额资金。若借款人所指定的还款账户余额不足以支付应还款项而导致还款失败的，因此造成的后果由借款人自行承担。
          <strong>
            <strong>
              如还款日扣款失败，系统会继续进行自动扣款，直至扣收成功为止。
            </strong>
          </strong>
        </p>
        <p>4、逾期</p>
        <p>
          （1）如借款人所指定的还款账户中资金不足以偿还已到期（含提前到期）的欠款，或借款人未于还款日24点前成功手动偿还，则已到期贷款逾期。
        </p>
        <p>
          （2）借款人理解并同意，
          <strong>
            <strong>贷款人有权单方面通知第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>且第三方支付机构</strong>
          </strong>
          <strong>
            <strong>或银行</strong>
          </strong>
          <strong>
            <strong>有权根据贷款人的指令对借款人</strong>
          </strong>
          <strong>
            <strong>所指定的还款账户</strong>
          </strong>
          <strong>
            <strong>
              采取划扣应还款项或停止支付、提现等限制措施。账户限制措施及自动扣款在借款人
            </strong>
          </strong>
          <strong>
            <strong>还清贷款本息</strong>
          </strong>
          <strong>
            <strong>
              前会持续实施，可能导致借款人的损失由借款人自行承担。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>5</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>提前还款</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>借款人</strong>
          </strong>
          <strong>
            <strong>可</strong>
          </strong>
          <strong>
            <strong>提前</strong>
          </strong>
          <strong>
            <strong>偿还</strong>
          </strong>
          <strong>
            <strong>全部贷款本金、利息、费用等款项</strong>
          </strong>
          <strong>
            <strong>，贷款人不收取提前还款违约金。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>&nbsp;</strong>
          </strong>
        </p>
        <p>
          6、借款人偿还的资金
          <strong>
            <strong>一般情况下将按照如下顺序清偿：</strong>
          </strong>
        </p>
        <p>（1）代收担保费（如有）；</p>
        <p>（2）利息；</p>
        <p>（3）罚息；</p>

        <p>（4）本金；</p>
        <p>
          （5）其他款项（包括但不限于贷款人为借款人垫付的费用及实现债权的费用，如诉讼费、律师代理费、公证费、催收费用等）。
        </p>
        <p>
          <strong>
            <strong>7、借款人理解并同意</strong>
          </strong>
          <strong>
            <strong>，当借款人逾期超过90天（不含当日），贷款人有权自行</strong>
          </strong>
          <strong>
            <strong>将清偿顺序变更为：本金、利息、罚息、</strong>
          </strong>
          <strong>
            <strong>其他</strong>
          </strong>
          <strong>
            <strong>款项。上述变更无需另行通知借款人</strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
          <strong>
            <strong>
              对有2笔（含）以上借款到期的情况下，贷款人有权决定借款人所付款项偿还借款的顺序。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>九</strong>
          </strong>
          <strong>
            <strong>条借款人的信息授权</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、借款人的个人信息的查询、收集、使用</strong>
          </strong>
          <strong>
            <strong>及保</strong>
          </strong>
          <strong>
            <strong>存</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（1）借款人同意贷款人和/或</strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>
              授权、委派的第三方通过包括但不限于中国人民银行金融信用信息基础数据库、
            </strong>
          </strong>
          <strong>
            <strong>百行征信有限公司、</strong>
          </strong>
          <strong>
            <strong>
              互联网金融协会及信贷征信主管部门、其他依法设立的征信机构、公安部公民身份信息数据库、社保中心、公积金管理中心
            </strong>
          </strong>
          <strong>
            <strong>或</strong>
          </strong>
          <strong>
            <strong>
              其他合法展业的数据服务商等机构查询、打印、存储、验证借款人的
            </strong>
          </strong>
          <strong>
            <strong>个人基本资料、身份信息、</strong>
          </strong>
          <strong>
            <strong>运营商信息、</strong>
          </strong>
          <strong>
            <strong>银行卡信息、</strong>
          </strong>
          <strong>
            <strong>借贷信息、消费信息、财务信息</strong>
          </strong>
          <strong>
            <strong>
              、信用信息、社保账户流水、公积金账户流水、地理位置信息
            </strong>
          </strong>
          <strong>
            <strong>等</strong>
          </strong>
          <strong>
            <strong>为识别借款人身份和风险状况而需要了解的</strong>
          </strong>
          <strong>
            <strong>个人信息（包括可能对本人产生负面影响的不良信息）；</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（2）</strong>
          </strong>
          <strong>
            <strong>借款人同意贷款人</strong>
          </strong>
          <strong>
            <strong>和/或</strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>授权、委派的第三方</strong>
          </strong>
          <strong>
            <strong>收集、保存平台以</strong>
          </strong>
          <strong>
            <strong>加密数据</strong>
          </strong>
          <strong>
            <strong>技术</strong>
          </strong>
          <strong>
            <strong>传输</strong>
          </strong>
          <strong>
            <strong>的</strong>
          </strong>
          <strong>
            <strong>借款人的相关信息。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>3</strong>
          </strong>
          <strong>
            <strong>）借款人同意贷款人和/或</strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>
              授权、委派的第三方通过查询、收集借款人的信息或对借款人的信息进行加工、分析和处理、核验，用于贷款服务的风险控制
            </strong>
          </strong>
          <strong>
            <strong>、履行反洗钱、反欺诈义务</strong>
          </strong>
          <strong>
            <strong>或维护、改善贷款服务。</strong>
          </strong>
          <strong>
            <strong>
              为了提升服务效率，借款人同意贷款人可委托专业机构在授权范围内对借款人的信息进行加工、分析和处理，协助完成本协议项下贷款人提供的部分服务或职责。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>4</strong>
          </strong>
          <strong>
            <strong>）</strong>
          </strong>
          <strong>
            <strong>
              借款人同意贷款人和/或其授权、委派的第三方在法律法规和监管机构允许的范围和期限内按要求保存所收集的借款人的全部个人信息。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2、借款人的个人信息</strong>
          </strong>
          <strong>
            <strong>共享</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>1</strong>
          </strong>
          <strong>
            <strong>）借款人同意贷款人和/或</strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>授权、委派的第三方将收集、</strong>
          </strong>
          <strong>
            <strong>保存</strong>
          </strong>
          <strong>
            <strong>的借款人</strong>
          </strong>
          <strong>
            <strong>的</strong>
          </strong>
          <strong>
            <strong>信息提供给</strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>
              用于向借款人提供进一步的服务，如客户服务、支付结算服务、信贷催收服务
            </strong>
          </strong>
          <strong>
            <strong>、定向推送服务</strong>
          </strong>
          <strong>
            <strong>等。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>2</strong>
          </strong>
          <strong>
            <strong>
              ）借款人同意贷款人根据有关监管规定，将与本协议有关的
            </strong>
          </strong>
          <strong>
            <strong>借款人</strong>
          </strong>
          <strong>
            <strong>信息和借款人</strong>
          </strong>
          <strong>
            <strong>的</strong>
          </strong>
          <strong>
            <strong>
              其他相关信息报送相关监管部门和监管信息系统、行业自律组织
            </strong>
          </strong>
          <strong>
            <strong>和其他合法有权机构</strong>
          </strong>
          <strong>
            <strong>，供监管部门使用和借款人授权查询使用。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>3</strong>
          </strong>
          <strong>
            <strong>
              ）借款人同意贷款人根据有关法律法规、监管规定，将与本协议有关的信息和借款人
            </strong>
          </strong>
          <strong>
            <strong>的</strong>
          </strong>
          <strong>
            <strong>其他相关信息提供给中国人民银行征信系统</strong>
          </strong>
          <strong>
            <strong>、百行征信有限公司</strong>
          </strong>
          <strong>
            <strong>和其他依法设立的信用信息数据库。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>4</strong>
          </strong>
          <strong>
            <strong>）</strong>
          </strong>
          <strong>
            <strong>
              借款人理解并同意，授权贷款人和/或其授权、委派的第三方取得借款人的个人信息，有可能产生不利于借款人的后果，如
            </strong>
          </strong>
          <strong>
            <strong>
              借款人违反本合同约定时，贷款人除依法追究借款人的违约责任外，有权将借款人的违约行为录入行业监管系统和征信系统。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>5</strong>
          </strong>
          <strong>
            <strong>
              ）借款人理解并同意，若借款人未按期履行还款义务产生逾期，贷款人有权对借款人采取催收措施或委托第三方采取催收措施，且有权将借款人的个人信息提供给包括但不限于催收机构、律师事务所等第三方机构。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（</strong>
          </strong>
          <strong>
            <strong>6</strong>
          </strong>
          <strong>
            <strong>
              ）借款人理解并同意，若借款人未按期履行还款义务产生逾期，贷款人或
            </strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>
              委托的第三方，有权将借款人的违约情况以及还款义务告知借款人提供的联系人。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              （7）借款人理解并同意，当借款人逾期欠款或存在无法自行按时还款的情形，且贷款人或其委托的第三方尝试与借款人联系但未取得联系或联系困难的情况下，贷款人或其委托的第三方可与借款人提供的联系人或通过第三方服务机构合作获知的借款人的其他联系人取得联系，询问借款人的联系方式或在征得对方同意的前提下请其向借款人转达信息，提示借款人及时履约。当贷款人或其委托的第三方通过以上方式仍无法联系到借款人时，贷款人或其委托的第三方有权通过银行流水查询、网络查询、外访排查、共债方信息共享等其他任何合法方式进行失联修复，因失联修复而产生的一切费用将由借款人承担。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>十</strong>
          </strong>
          <strong>
            <strong>条</strong>
          </strong>
          <strong>
            <strong>息费</strong>
          </strong>
          <strong>
            <strong>计收规则</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、</strong>
          </strong>
          <strong>
            <strong>基于本协议</strong>
          </strong>
          <strong>
            <strong>第一条约定的息费标准，</strong>
          </strong>
          <strong>
            <strong>贷款人</strong>
          </strong>
          <strong>
            <strong>与借款人特别约定计收规则如下：</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（1）利息：</strong>
          </strong>
          <strong>
            <strong>
              以本协议第一条约定为准。综合年化利率据本协议签署日前最新一期全国银行间同业拆借中心公布的1年期贷款市场报价利率（LPR）
            </strong>
          </strong>
          <strong>
            <strong>加减点</strong>
          </strong>
          <strong>
            <strong>确定。已发放贷款的利率不</strong>
          </strong>
          <strong>
            <strong>受</strong>
          </strong>
          <strong>
            <strong>利率调整的影响。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（2）</strong>
          </strong>
          <strong>
            <strong>罚息：从逾期之日起</strong>
          </strong>
          <strong>
            <strong>，贷款人有权</strong>
          </strong>
          <strong>
            <strong>对逾期贷款</strong>
          </strong>
          <strong>
            <strong>本金</strong>
          </strong>
          <strong>
            <strong>按</strong>
          </strong>
          <strong>
            <strong>本协议第一条</strong>
          </strong>
          <strong>
            <strong>约定的利率加收</strong>
          </strong>
          <strong>
            <strong>50%</strong>
          </strong>
          <strong>
            <strong>计收</strong>
          </strong>
          <strong>
            <strong>逾期</strong>
          </strong>
          <strong>
            <strong>罚息，对于不能按时支付的利息，贷款人有权按照</strong>
          </strong>
          <strong>
            <strong>前述</strong>
          </strong>
          <strong>
            <strong>罚息标准计收复利</strong>
          </strong>
          <strong>
            <strong>，</strong>
          </strong>
          <strong>
            <strong>直至</strong>
          </strong>
          <strong>
            <strong>借款人</strong>
          </strong>
          <strong>
            <strong>清偿逾期本息为止。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（3</strong>
          </strong>
          <strong>
            <strong>）</strong>
          </strong>
          <strong>
            <strong>代收担保费（如有）：</strong>
          </strong>
          <strong>
            <strong>借款</strong>
          </strong>
          <strong>
            <strong>服务费=贷款本金*</strong>
          </strong>
          <strong>
            <strong>代收担保费</strong>
          </strong>
          <strong>
            <strong>率，代收担保费率以本协议第一条约定为准</strong>
          </strong>
          <strong>
            <strong>，代收担保费将在第一期还款时全额收取</strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>
              贷款人有权随时修改或新增费用项目或标准，费用项目或标准修改或新增后将通过平台进行公告，若借款人不同意修改或新增费用项目或标准可
            </strong>
          </strong>
          <strong>
            <strong>申请全额提前还款，否则</strong>
          </strong>
          <strong>
            <strong>则视为借款人已同意修改或新增费用项目或标准。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>一</strong>
          </strong>
          <strong>
            <strong>条陈述与保证</strong>
          </strong>
        </p>
        <p>
          1、借款人向贷款人做出如下陈述和保证，且该陈述和保证应视同在贷款人每次按照本协议的约定向借款人提供贷款时，由借款人重复做出并在借款期限内持续有效：
        </p>
        <p>
          （1）借款人为自然人，具备签订和履行本合同所需的完全民事权利能力和行为能力；签署和履行本合同系基于借款人的真实意思表示，已对借款人具有法律约束力。
        </p>
        <p>
          （2）借款人签署和履行本协议，并不违反任何对借款人及借款人的资产有约束力的法律法规或生效的司法裁判/仲裁裁决，不违反任何对借款人有约束力的合同、协议、约定或承诺，不侵犯任何第三方的合法权益。
        </p>
        <p>
          （3）借款人承诺妥善保管本人的账号、密码、绑定的手机号码、手机校验码等与办理及使用借款过程中的一切有关信息。借款人应确保不向其他任何人泄露有关账号、密码、手机验证码等相关信息。对于因账号、密码、手机验证码泄露所致的损失，由借款人自行承担。如借款人发现有他人冒用或盗用本人账号及密码或任何其他未经合法授权之情形时，应立即通知平台和/或贷款人，要求其暂停相关服务。同时，借款人理解平台和/或贷款人对相应的请求采取行动需要合理期限，在平台和/或贷款人对借款人相应的请求采取行动之前，针对向平台账户或收款账户已执行的指令及/或所导致的借款人的损失，平台和/或贷款人不承担责任。
        </p>
        <p>（4）借款人承诺按照本协议约定的贷款用途使用贷款，并保证：</p>
        <p>
          （a）不得将所借款项用于任何违法活动（包括但不限于赌博、吸毒、贩毒、卖淫嫖娼等），否则一经发现，贷款人将立即向公安等有关行政机关举报，追回借款并追究借款人的刑事责任；
        </p>
        <p>
          （b）不得将所借款项用于金融市场（包括但不限于投资股票、基金、债券、期货等金融产品及其衍生品）、房地产市场，以及其他国家法律法规禁止贷款进入的领域，也不得将所借款项用于信用卡取现或办理信用卡分期业务。若借款人出现上述情形则视为违约，贷款人有权据此提前终止协议收回贷款，并采取其他违约处理措施；
        </p>
        <p>
          （c）若因贷款人监管机构开展检查或贷款人自查等原因，需补充提供贷款用途证明材料及其他文件资料的或者贷款人自行或授权、委托第三方对贷款期间借款人的资信状况、重大财产处分行为进行监督的，借款人承诺积极配合并按贷款人和/或授权、委托的第三方的要求提供相关的收入状况证明、凭证及合同等资料。如拒不配合或无法提供或提供材料不符要求的，贷款人有权据此宣布贷款提前到期。借款人应立即结清全部贷款本息及其他费用，否则视为借款人违约，贷款人有权采取其他违约处理措施。
        </p>
        <p>
          （5）借款人在签署和履行本合同过程中恪守诚实守信原则，借款人所出具的涉及借款人以及涉及本合同的所有文件、信息和资料均为真实、有效、完整、准确而无任何隐瞒的。
        </p>
        <p>
          （6）借款人在贷款发放后因使用该贷款资金与他人发生的任何纠纷，均与贷款人无关。借款人应履行按时还款义务以及其他合同义务。
        </p>
        <p>
          （7）自本协议签署之日起，至借款人在本协议项下的债务全部清偿完毕之前，未经贷款人书面同意，借款人不得：（a）转让（包括出售、赠与、抵债、交换等形式）、抵押、质押或以其他方式处分借款人的重大资产以及为他人债务提供保证；（b）签署对履行本合同项下义务的能力有重大不利影响的合同、协议或承担具有重大不利影响的有关义务。
        </p>
        <p>
          （8）借款人在本协议签署时没有隐瞒已经发生或将要发生的任何影响或可能影响借款人签署或履行本合同、或可能对借款人的财务状况产生不利影响的诉讼案件、仲裁案件、行政程序、财产保全措施、强制执行程序或其他不利影响的事件；并且，借款人将在本协议履行期内持续向贷款人承担上述信息的及时披露义务。在发生前述事件时，立即通知贷款人并详细说明所构成的影响及已采取或计划采取的补救措施，并于获悉该事件发生之日起3个工作日内将书面通知、证明和说明文件原件送达贷款人。
        </p>
        <p>
          （9）一旦借款人的住址、或联系地址、联系电话等信息发生变更，自该变更发生之日起5个工作日内书面通知贷款人。
        </p>
        <p>2、贷款人的陈述和保证</p>
        <p>贷款人向借款人做出如下陈述和保证，截至本合同签订时：</p>
        <p>
          （1）其在本合同项下向借款人收取的所有借款成本与贷款本金的比例折算所得的年化综合实际利率不超过法律法规、监管规定、司法解释规定的上限。
        </p>
        <p>
          （2）不再与借款人在本合同外约定和收取与本合同贷款相关的利息和费用，但为提高借款人通过贷款审批的成功率，贷款人或其委托的第三方可为借款人推荐保险公司或担保公司，借款人同意并向保险公司或担保公司支付的费用不属于本条约定的与贷款有关的费用；
        </p>
        <p>
          （3）根据业务需要，贷款人可能需委托其他第三方对本贷款业务提供技术支持。
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>二</strong>
          </strong>
          <strong>
            <strong>条违约责任</strong>
          </strong>
        </p>
        <p>1、借款人的违约责任</p>
        <p>
          借款人因违反本合同约定，造成贷款不能及时足额偿还，贷款人有权采取下列一种或数种措施：
        </p>
        <p>（1）要求借款人限期纠正违约行为；</p>
        <p>（2）单方面调整借款人的还款方式；</p>
        <p>（3）单方面调整借款人的贷款支付方式；</p>
        <p>
          （4）单方面通知第三方支付机构对借款人的第三方支付账户及与之绑定的银行账户采取划扣应还款项或停止支付、提现等限制措施。账户限制措施及自动扣款在借款人结清贷款前会持续实施，可能导致借款人的损失由借款人自行承担；
        </p>
        <p>
          （5）要求合作机构协助贷款人采取必要的救济措施，包括但不限于停止服务、暂扣相关材料等措施；
        </p>
        <p>
          （6）宣布本合同项下借款人已获得发放的贷款本息立即部分或全部提前到期，未发放部分取消贷款额度，并有权要求借款人立即偿还本合同项下贷款人宣布提前到期的所有到期及未到期贷款的本金、利息和其他应付款项，贷款人宣布提前到期的贷款的利息按贷款发放日（不含该日）至本协议第一条约定的借款期限届满日（含该日）之间的实际天数，以提前到期贷款金额为基数，按本合同约定利率计算；
        </p>
        <p>
          （7）要求借款人赔偿因违约而给贷款人造成的损失，包括但不限于因实现债权而导致的诉讼费、律师费、公证费、执行费等相关费用损失；
        </p>
        <p>（8）要求借款人清偿贷款本金、利息、罚息、各项费用、违约金等；</p>
        <p>
          （9）将借款人的违约记录计入贷款人内部黑名单系统，同步向行业监管系统和中国人民银行等征信系统报送；
        </p>
        <p>（10）采取法律法规允许的其他必要措施。</p>
        <p>2、贷款人的违约责任</p>
        <p>
          （1）满足本合同约定贷款发放条件，贷款人无理由延期或者拒不发放贷款的，应赔偿借款人因此而发生的直接经济损失。
        </p>
        <p>
          （2）要求贷款人赔偿因其违约而给借款人造成的实际损失，包括但不限于因实现债权而导致的诉讼费、律师费、公证费、执行费等相关费用损失，不包含预期损失。
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>三</strong>
          </strong>
          <strong>
            <strong>条债权债务的转让</strong>
          </strong>
        </p>
        <p>
          未经贷款人书面同意，借款人不得将本协议项下的权利和义务转让给任何第三方。贷款人有权无需事先通知且无需征得借款人的同意而将本协议项下的权利和义务全部或部分转让给第三方。
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>四</strong>
          </strong>
          <strong>
            <strong>条平台及</strong>
          </strong>
          <strong>
            <strong>平台信息展示、</strong>
          </strong>
          <strong>
            <strong>协议签署与变更</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、平台及平台信息展示</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（1）</strong>
          </strong>
          <strong>
            <strong>本协议项下的&ldquo;</strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>&rdquo;</strong>
          </strong>
          <strong>
            <strong>是指</strong>
          </strong>
          <strong>
            <strong>协助贷款人与借款人完成贷款流程、</strong>
          </strong>
          <strong>
            <strong>传递</strong>
          </strong>
          <strong>
            <strong>和展示相关信息，</strong>
          </strong>
          <strong>
            <strong>并</strong>
          </strong>
          <strong>
            <strong>接受贷款人委托履行本协议项下部分权利义务的</strong>
          </strong>
          <strong>
            <strong>
              以互联网为载体的提供个人消费贷款产品信息与金融服务的平台，包括
            </strong>
          </strong>
          <strong>
            <strong>&ldquo;自由贷&rdquo;</strong>
          </strong>
          <strong>
            <strong>APP</strong>
          </strong>
          <strong>
            <strong>、小程序</strong>
          </strong>
          <strong>
            <strong>等移动客户端、软件或</strong>
          </strong>
          <strong>
            <strong>贷款人</strong>
          </strong>
          <strong>
            <strong>认可的第三方合作机构现在或将来可能开发</strong>
          </strong>
          <strong>
            <strong>或运营</strong>
          </strong>
          <strong>
            <strong>的软件。</strong>
          </strong>
        </p>
        <p>
          （2）借款人知晓并同意，平台对于借款人的权利和义务，已在借款人与平台另行签署的相关协议、平台页面规则中进行了详细的展示及记载。除借款人与平台另有约定外，平台不承担本协议项下任何责任。
        </p>
        <p>
          （3）贷款人和借款人一致同意本协议约定的借款基本信息及收费信息等要素，如与平台展示的不一致，以平台展示为准。
        </p>
        <p>2、协议签署</p>
        <p>
          <strong>
            <strong>本协议</strong>
          </strong>
          <strong>
            <strong>以数据电文形式</strong>
          </strong>
          <strong>
            <strong>在平台上完成签署，</strong>
          </strong>
          <strong>
            <strong>各方均认可其法律效力。</strong>
          </strong>
          借款人通过平台申请贷款服务时，
          <strong>
            <strong>在</strong>
          </strong>
          <strong>
            <strong>网络页面点击确认</strong>
          </strong>
          <strong>
            <strong>本</strong>
          </strong>
          <strong>
            <strong>协议</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>交易密码</strong>
          </strong>
          <strong>
            <strong>或以其他方式表示接受</strong>
          </strong>
          <strong>
            <strong>时</strong>
          </strong>
          <strong>
            <strong>本协议生效。</strong>
          </strong>
          <strong>
            <strong>借款人在</strong>
          </strong>
          <strong>
            <strong>平台上提交相关申请、回复、确认、指令</strong>
          </strong>
          <strong>
            <strong>等</strong>
          </strong>
          <strong>
            <strong>均构成借款人在本协议项下有效的意思表示</strong>
          </strong>
          <strong>
            <strong>和</strong>
          </strong>
          <strong>
            <strong>本协议的有效部分，与本协议有同等效力。</strong>
          </strong>
          <strong>
            <strong>且上述</strong>
          </strong>
          <strong>
            <strong>行为均视为</strong>
          </strong>
          <strong>
            <strong>借款人</strong>
          </strong>
          <strong>
            <strong>本人行为。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>3</strong>
          </strong>
          <strong>
            <strong>、协议变更</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>除另有约定</strong>
          </strong>
          <strong>
            <strong>或法律法规或监管规定另有强制性规定</strong>
          </strong>
          <strong>
            <strong>外，</strong>
          </strong>
          <strong>
            <strong>因</strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>进行系统升级</strong>
          </strong>
          <strong>
            <strong>或</strong>
          </strong>
          <strong>
            <strong>服务升级</strong>
          </strong>
          <strong>
            <strong>或者贷款政策变更等原因</strong>
          </strong>
          <strong>
            <strong>需</strong>
          </strong>
          <strong>
            <strong>变更</strong>
          </strong>
          <strong>
            <strong>本</strong>
          </strong>
          <strong>
            <strong>协议条款时，</strong>
          </strong>
          <strong>
            <strong>除法律法规或监管规定另有强制性规定外，</strong>
          </strong>
          <strong>
            <strong>变更的内容一经更新</strong>
          </strong>
          <strong>
            <strong>并以本协议约定的通知与送达方式送达借款人时</strong>
          </strong>
          <strong>
            <strong>
              立即生效。若借款人不同意上述变更，可向贷款人申请终止本协议
            </strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
          <strong>
            <strong>若借款人在变更通知</strong>
          </strong>
          <strong>
            <strong>送达</strong>
          </strong>
          <strong>
            <strong>
              后仍使用本服务，视为借款人已接受上述变更，相关条款根据变更自动修改，各方无需签订补充协议。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>五</strong>
          </strong>
          <strong>
            <strong>条免责及责任限制</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、若</strong>
          </strong>
          <strong>
            <strong>
              发生贷款人对借款人指令识别错误或执行错误，则借款人须在知道或应当知道错误发生后的三个自然日内书面通知贷款人和/或
            </strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>并尽力采取措施防止损失扩大，贷款人和/或</strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>应尽快调查处理并在合理可行的范围内采取补救措施。</strong>
          </strong>
          如贷款人发现对借款人指令识别错误或执行错误或数据展示错误，贷款人有权进行主动修正，同时贷款人有权委托平台向借款人以平台站内信或手机短信等形式发送修正通知，该修正通知在平台向借款人发送后即行生效，借款人不能因此向贷款人主张否认贷款债权的法律效力。
          <strong>
            <strong>贷款人和/或</strong>
          </strong>
          <strong>
            <strong>平台</strong>
          </strong>
          <strong>
            <strong>对间接损失、履行利益、后果性损害、非财产损害、不能</strong>
          </strong>
          <strong>
            <strong>预</strong>
          </strong>
          <strong>
            <strong>
              见的损失及借款人未及时通知导致的扩大损失不承担赔偿责任
            </strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2、</strong>
          </strong>
          <strong>
            <strong>不可抗力</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（1）</strong>
          </strong>
          <strong>
            <strong>
              不可抗力是指不能预见、不能避免并不能克服的客观情况，包括但不限于法律法规的调整、电信部门技术调整和线路故障、恶意软件、病毒、黑客攻击、台风等自然灾害、行业监管部门监管要求的变化以及司法行为等为协议任何一方所无法抗拒的外力。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（2）</strong>
          </strong>
          <strong>
            <strong>
              任何一方如因不可抗力导致不能履行本合同约定义务或其履约遭延误，遭遇不可抗力的一方应在受到不可抗力影响之日起5日内书面通知另一方，并提供行政等权力相关出具的不可抗力发生及其影响的证明。双方应采取一切必要且合理的努力预防和减轻损失。因不可抗力造成本合同所涉业务无法继续开展的，遭受不可抗力的一方应及时通知对方并配合对方处理后续事宜。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（3）</strong>
          </strong>
          <strong>
            <strong>
              不可抗力的影响结束后，双方另有约定外，应继续履行本合同。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>六</strong>
          </strong>
          <strong>
            <strong>条税费</strong>
          </strong>
        </p>
        <p>
          除本协议另有约定外，所有涉及本协议及其履行所发生的税费均由借款人及贷款人按法律法规的规定各自负担。
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>七</strong>
          </strong>
          <strong>
            <strong>条通知与送达</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、</strong>
          </strong>
          <strong>
            <strong>借款人应确保在平台上提供的</strong>
          </strong>
          <strong>
            <strong>联系人姓名、</strong>
          </strong>
          <strong>
            <strong>通讯地址、家庭住址、工作单位地址、</strong>
          </strong>
          <strong>
            <strong>身份证地址、</strong>
          </strong>
          <strong>
            <strong>
              手机号码、电子邮箱、传真号码、微信号、平台用户名等信息
            </strong>
          </strong>
          <strong>
            <strong>完整、</strong>
          </strong>
          <strong>
            <strong>
              准确、有效。上述地址均为本协议涉及和有关的各类通知以及就本协议发生纠纷时相关文件和法律文书送达时的送达地址。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2、</strong>
          </strong>
          <strong>
            <strong>各方一致确认，</strong>
          </strong>
          <strong>
            <strong>上述借款人提供的</strong>
          </strong>
          <strong>
            <strong>
              联系地址适用范围包括但不限于双方之间的各类告知书、通知书、往来函件、工作联系单、协议文件、诉讼文书，送达主体可以是合同各方、人民法院及各行政机关。也包括但不限于调解、一审、二审、再审、执行等各个程序和阶段。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              送达主体按照上述送达地址进行送达，视为有效送达；采用邮寄送达的，以文书寄出之日后的第二日视为送达之日；直接送达的，送达人当场在送达回证上记明情况之日视为送达之日；拒绝签收的，以文书寄出之日后的第二日视为送达之日；由他人代收的，以文书寄出之日后的第二日视为送达之日。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>
              上述送达地址、受送达人、联系方式发生变更的，变更一方应履行通知义务，因当事人送达地址变更后未及时书面告知，导致未能被当事人实际接收的，邮寄送达的，以文书寄出之日后的第二日视为送达之日；直接送达的，送达人当场在送达回证上记明情况之日视为送达之日；拒绝签收的，以文书寄出之日后的第二日视为送达之日；由他人代收的，以文书寄出之日后的第二日视为送达之日。已履行送达地址变更通知义务的，以变更后的送达地址为有效送达地址。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>借款人同意并确认上述通知和送达的条款且无异议。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第十</strong>
          </strong>
          <strong>
            <strong>八</strong>
          </strong>
          <strong>
            <strong>条可分割性</strong>
          </strong>
        </p>
        <p>
          如果在任何时候根据届时有效的法律，本合同的一个或多个条款在任何方面成为非法、无效或不可执行，本合同其他条款的合法性、有效性或可执行性不因此在任何方面受到影响或损害。
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>十九</strong>
          </strong>
          <strong>
            <strong>条法律适用与争议管辖</strong>
          </strong>
        </p>
        <p>
          协议适用中华人民共和国法律法规。本协议引起及与本协议有关的争议，双方应友好协商解决，
          <strong>
            <strong>协商不成</strong>
          </strong>
          <strong>
            <strong>时</strong>
          </strong>
          <strong>
            <strong>任何一方均可选择以下方式解决：</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（1）诉讼方式</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>由本协议签署</strong>
          </strong>
          <strong>
            <strong>地或实际履行地</strong>
          </strong>
          <strong>
            <strong>人民法院管辖或根据级别管辖原则由其上级法院管辖。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>本协议签署地以第一条约定为准，实际履行地为</strong>
          </strong>
          <strong>
            <strong>xx省xx市</strong>
          </strong>
          <strong>
            <strong>。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>（2）仲裁方式</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>如果协商无法解决，任何一方均可将争议提交</strong>
          </strong>
          <strong>
            <strong>【南京仲裁委】</strong>
          </strong>
          <strong>
            <strong>，按照</strong>
          </strong>
          <strong>
            <strong>其</strong>
          </strong>
          <strong>
            <strong>仲裁规则</strong>
          </strong>
          <strong>
            <strong>进行</strong>
          </strong>
          <strong>
            <strong>仲裁。仲裁裁决是终局的，对双方均有约束力。</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>第</strong>
          </strong>
          <strong>
            <strong>二十</strong>
          </strong>
          <strong>
            <strong>条</strong>
          </strong>
          <strong>
            <strong>其他</strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>1、</strong>
          </strong>
          <strong>
            <strong>借</strong>
          </strong>
          <strong>
            <strong>据</strong>
          </strong>
          <strong>
            <strong>明细</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>
              还款计划、交易明细均为本协议附件，与本协议正文具有同等法律效力。
            </strong>
          </strong>
        </p>
        <p>
          <strong>
            <strong>2</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>在借款人</strong>
          </strong>
          <strong>
            <strong>申请</strong>
          </strong>
          <strong>
            <strong>、</strong>
          </strong>
          <strong>
            <strong>使用</strong>
          </strong>
          <strong>
            <strong>贷款时</strong>
          </strong>
          <strong>
            <strong>，除遵守本协议正文的相关约定外，</strong>
          </strong>
          <strong>
            <strong>申请流程</strong>
          </strong>
          <strong>
            <strong>网页相关约定及平台业务规则等亦同时需要遵守。</strong>
          </strong>
        </p>
      </div>
    </div>
  )
}

export default body
